const episodes = [
    /* SEASON 1 */
    { name: "Episode 1", season: 1, episode: 1, video: "shows/JJK/JUJUTSU KAISEN - E01.mkv" },
    { name: "Episode 2", season: 1, episode: 2, video: "shows/JJK/JUJUTSU KAISEN - E02.mkv" },
    { name: "Episode 3", season: 1, episode: 3, video: "shows/JJK/JUJUTSU KAISEN - E03.mkv" },
    { name: "Episode 4", season: 1, episode: 4, video: "shows/JJK/JUJUTSU KAISEN - E04.mkv" },
    { name: "Episode 5", season: 1, episode: 5, video: "shows/JJK/JUJUTSU KAISEN - E05.mkv" },
    { name: "Episode 6", season: 1, episode: 6, video: "shows/JJK/JUJUTSU KAISEN - E06.mkv" },
    { name: "Episode 7", season: 1, episode: 7, video: "shows/JJK/JUJUTSU KAISEN - E07.mkv" },
    { name: "Episode 8", season: 1, episode: 8, video: "shows/JJK/JUJUTSU KAISEN - E08.mkv" },
    { name: "Episode 9", season: 1, episode: 9, video: "shows/JJK/JUJUTSU KAISEN - E09.mkv" },
    { name: "Episode 10", season: 1, episode: 10, video: "shows/JJK/JUJUTSU KAISEN - E10.mkv" },
    { name: "Episode 11", season: 1, episode: 11, video: "shows/JJK/JUJUTSU KAISEN - E11.mkv" },
    { name: "Episode 12", season: 1, episode: 12, video: "shows/JJK/JUJUTSU KAISEN - E12.mkv" },
    { name: "Episode 13", season: 1, episode: 13, video: "shows/JJK/JUJUTSU KAISEN - E13.mkv" },
    { name: "Episode 14", season: 1, episode: 14, video: "shows/JJK/JUJUTSU KAISEN - E14.mkv" },
    { name: "Episode 15", season: 1, episode: 15, video: "shows/JJK/JUJUTSU KAISEN - E15.mkv" },
    { name: "Episode 16", season: 1, episode: 16, video: "shows/JJK/JUJUTSU KAISEN - E16.mkv" },
    { name: "Episode 17", season: 1, episode: 17, video: "shows/JJK/JUJUTSU KAISEN - E17.mkv" },
    { name: "Episode 18", season: 1, episode: 18, video: "shows/JJK/JUJUTSU KAISEN - E18.mkv" },
    { name: "Episode 19", season: 1, episode: 19, video: "shows/JJK/JUJUTSU KAISEN - E19.mkv" },
    { name: "Episode 20", season: 1, episode: 20, video: "shows/JJK/JUJUTSU KAISEN - E20.mkv" },
    { name: "Episode 21", season: 1, episode: 21, video: "shows/JJK/JUJUTSU KAISEN - E21.mkv" },
    { name: "Episode 22", season: 1, episode: 22, video: "shows/JJK/JUJUTSU KAISEN - E22.mkv" },
    { name: "Episode 23", season: 1, episode: 23, video: "shows/JJK/JUJUTSU KAISEN - E23.mkv" },
    { name: "Episode 24", season: 1, episode: 24, video: "shows/JJK/JUJUTSU KAISEN - E24.mkv" },

    /* SEASON 2 */
    { name: "Episode 25", season: 2, episode: 1, video: "shows/JJK/JUJUTSU KAISEN - E25.mkv" },
    { name: "Episode 26", season: 2, episode: 2, video: "shows/JJK/JUJUTSU KAISEN - E26.mkv" },
    { name: "Episode 27", season: 2, episode: 3, video: "shows/JJK/JUJUTSU KAISEN - E27.mkv" },
    { name: "Episode 28", season: 2, episode: 4, video: "shows/JJK/JUJUTSU KAISEN - E28.mkv" },
    { name: "Episode 29", season: 2, episode: 5, video: "shows/JJK/JUJUTSU KAISEN - E29.mkv" },
    { name: "Episode 30", season: 2, episode: 6, video: "shows/JJK/JUJUTSU KAISEN - E30.mkv" },
    { name: "Episode 31", season: 2, episode: 7, video: "shows/JJK/JUJUTSU KAISEN - E31.mkv" },
    { name: "Episode 32", season: 2, episode: 8, video: "shows/JJK/JUJUTSU KAISEN - E32.mkv" },
    { name: "Episode 33", season: 2, episode: 9, video: "shows/JJK/JUJUTSU KAISEN - E33.mkv" },
    { name: "Episode 34", season: 2, episode: 10, video: "shows/JJK/JUJUTSU KAISEN - E34.mkv" },
    { name: "Episode 35", season: 2, episode: 11, video: "shows/JJK/JUJUTSU KAISEN - E35.mkv" },
    { name: "Episode 36", season: 2, episode: 12, video: "shows/JJK/JUJUTSU KAISEN - E36.mkv" },
    { name: "Episode 37", season: 2, episode: 13, video: "shows/JJK/JUJUTSU KAISEN - E37.mkv" },
    { name: "Episode 38", season: 2, episode: 14, video: "shows/JJK/JUJUTSU KAISEN - E38.mkv" },
    { name: "Episode 39", season: 2, episode: 15, video: "shows/JJK/JUJUTSU KAISEN - E39.mkv" },
    { name: "Episode 40", season: 2, episode: 16, video: "shows/JJK/JUJUTSU KAISEN - E40.mkv" },
    { name: "Episode 41", season: 2, episode: 17, video: "shows/JJK/JUJUTSU KAISEN - E41.mkv" },
    { name: "Episode 42", season: 2, episode: 18, video: "shows/JJK/JUJUTSU KAISEN - E42.mkv" },
    { name: "Episode 43", season: 2, episode: 19, video: "shows/JJK/JUJUTSU KAISEN - E43.mkv" },
    { name: "Episode 44", season: 2, episode: 20, video: "shows/JJK/JUJUTSU KAISEN - E44.mkv" },
    { name: "Episode 45", season: 2, episode: 21, video: "shows/JJK/JUJUTSU KAISEN - E45.mkv" },
    { name: "Episode 46", season: 2, episode: 22, video: "shows/JJK/JUJUTSU KAISEN - E46.mkv" },
    { name: "Episode 47", season: 2, episode: 23, video: "shows/JJK/JUJUTSU KAISEN - E47.mkv" },

    /* SEASON 3 */
    { name: "Episode 48", season: 3, episode: 1, video: "shows/JJK/JUJUTSU KAISEN - E48.mkv" },
    { name: "Episode 49", season: 3, episode: 2, video: "shows/JJK/JUJUTSU KAISEN - E49.mkv" },
    { name: "Episode 50", season: 3, episode: 3, video: "shows/JJK/JUJUTSU KAISEN - E50.mkv" },
    { name: "Episode 51", season: 3, episode: 4, video: "shows/JJK/JUJUTSU KAISEN - E51.mkv" },
    { name: "Episode 52", season: 3, episode: 5, video: "shows/JJK/JUJUTSU KAISEN - E52.mkv" },
    { name: "Episode 53", season: 3, episode: 6, video: "shows/JJK/JUJUTSU KAISEN - E53.mkv" },
    { name: "Episode 54", season: 3, episode: 7, video: "shows/JJK/JUJUTSU KAISEN - E54.mkv" },
    { name: "Episode 55", season: 3, episode: 8, video: "shows/JJK/JUJUTSU KAISEN - E55.mkv" },
    { name: "Episode 56", season: 3, episode: 9, video: "shows/JJK/JUJUTSU KAISEN - E56.mkv" },
    { name: "Episode 57", season: 3, episode: 10, video: "shows/JJK/JUJUTSU KAISEN - E57.mkv" },
    { name: "Episode 58", season: 3, episode: 11, video: "shows/JJK/JUJUTSU KAISEN - E58.mkv" },
    { name: "Episode 59", season: 3, episode: 12, video: "shows/JJK/JUJUTSU KAISEN - E59.mkv" }
];
